Update About Us
AY2122S1-CS2103T-W12-3/tp pull request #12
Opened 2021-09-25 08:01 UTC by calvintanwj

2021-09-26 13:07 UTC, NicolasCwy requested changes
lgtm! Just need to change the portfolio page

2021-09-26 13:07 UTC, NicolasCwy commented on docs/team/calvintanwj.md
> +### Project: AddressBook Level 3
Can amend this to Pocket Hotel and keep the parts relevant to you!

2021-09-29 04:55 UTC, NicolasCwy requested changes
lgtm! Just need to change the portfolio page

2021-09-29 05:01 UTC, calvintanwj commented on docs/team/calvintanwj.md
> +### Project: AddressBook Level 3
Done

2021-09-29 05:08 UTC, NicolasCwy approved these changes
Lgtm

2021-09-30 01:49 UTC, NicolasCwy commented on docs/team/calvintanwj.md
> +      * Added and tweaked user stories
Should this be use cases?

2021-09-30 01:50 UTC, NicolasCwy requested changes
LGTM

2021-09-30 01:51 UTC, NicolasCwy approved these changes

2021-09-30 12:06 UTC, merged