Update UG, Add Command, Command Summary, Constraints
AY2122S1-CS2103T-W12-3/tp pull request #29
Opened 2021-09-30 05:56 UTC by alyssa-savier

2021-09-30 12:19 UTC, NicolasCwy requested changes
Small formatting issue!

2021-09-30 12:19 UTC, NicolasCwy commented on docs/UserGuide.md
> +Format: `add n/<NAME> pn/<PASSPORT_NUMBER> [p/<PHONE_NUMBER>] [r/<ROOM_NUMBER>]`/ `add n/<NAME> sid/<STAFF_ID> [p/<PHONE_NUMBER>] [r/<ROOM_NUMBER>]`
Check out Jeremy's PR #27 for the format!

2021-09-30 12:57 UTC, NicolasCwy approved these changes

2021-10-01 02:10 UTC, NicolasCwy approved these changes
LGTM, I will change the format on my side

2021-10-01 02:14 UTC, bingcheng45 approved these changes
LGTM

2021-10-01 02:21 UTC, merged